### ISSUE TITLE
updating Seven20 to remoteStorage.js v0.7 release

### ISSUE THREAD

**Issue by michielbdejong** [KenEucker/seven20#1]
Hi @Epic720,

Good news: @nilclass tagged the release of remoteStorage.js version 0.7.0 yesterday. here is an example of how it works:
https://github.com/michielbdejong/remoteStorage.js/blob/master/example/minimal/index.html
so because sync is "behind" the modules with remoteStorage.js 0.7, the app architecture is a matter of:

putting domain code into the module (notes.js in the example)
send controller actions to the module
update the DOM only when the module gives you a change event

here are reference docs:
http://remotestoragejs.com/doc/code/files/remoteStorage-js.html

let me know what you think! it would be nice to update this so we can have Seven20 compatible with the latest lib before we add it on https://unhosted.org/apps/ :)

Also check out the updated 'root' module that https://github.com/nilclass/remotestorage-browser-example uses: https://github.com/RemoteStorage/remoteStorage.js/blob/master/src/modules/root.js

**Comment by KenEucker** [comment]
I'm on it!

**Comment by michielbdejong** [comment]
Issue more than a year old, closing.
